#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.22
#  in conjunction with Tcl version 8.6
#    Sep 09, 2019 12:27:36 PM CDT  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import prog_descr_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = ProgDesc (root)
    prog_descr_support.init(root, top)
    root.mainloop()

w = None
def create_ProgDesc(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = tk.Toplevel (root)
    top = ProgDesc (w)
    prog_descr_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_ProgDesc():
    global w
    w.destroy()
    w = None

class ProgDesc:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'

        top.geometry("600x450+359+183")
        top.title("Program Description")
        top.configure(background="#d9d9d9")

        self.ButtonClose = tk.Button(top)
        self.ButtonClose.place(relx=0.067, rely=0.867, height=30, width=68)
        self.ButtonClose.configure(activebackground="#ececec")
        self.ButtonClose.configure(activeforeground="#000000")
        self.ButtonClose.configure(background="#d9d9d9")
        self.ButtonClose.configure(disabledforeground="#a3a3a3")
        self.ButtonClose.configure(font="-family {Arial} -size 12")
        self.ButtonClose.configure(foreground="#000000")
        self.ButtonClose.configure(highlightbackground="#d9d9d9")
        self.ButtonClose.configure(highlightcolor="black")
        self.ButtonClose.configure(pady="0")
        self.ButtonClose.configure(text='''Close''')
        self.ButtonClose.configure(width=68)
        self.ButtonClose.bind('<Button-1>',lambda e:prog_descr_support.btn_close_prog_descrip(e))

        self.Label1 = tk.Label(top)
        self.Label1.place(relx=0.083, rely=0.089, height=24, width=305)
        self.Label1.configure(anchor='w')
        self.Label1.configure(background="#d9d9d9")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(font="-family {Arial} -size 12")
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(justify='right')
        self.Label1.configure(text='''Program Description''')
        self.Label1.configure(width=305)

if __name__ == '__main__':
    vp_start_gui()





