#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.22
#  in conjunction with Tcl version 8.6
#    Sep 19, 2019 03:55:29 PM CDT  platform: Windows NT
# This is Rev 2 of Stain Selection GUI

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import stain_selection_gui_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    stain_selection_gui_support.set_Tk_var()
    top = Toplevel1 (root)
    stain_selection_gui_support.init(root, top)
    root.mainloop()

w = None
def create_Toplevel1(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = tk.Toplevel (root)
    stain_selection_gui_support.set_Tk_var()
    top = Toplevel1 (w)
    stain_selection_gui_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Toplevel1():
    global w
    w.destroy()
    w = None

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'
        font9 = "-family {Arial} -size 12"

        top.geometry("802x654+306+124")
        top.title("Stain Selection Rev 2")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")

        self.ButtonInputImg = tk.Button(top)
        self.ButtonInputImg.place(relx=0.075, rely=0.031, height=30, width=141)
        self.ButtonInputImg.configure(activebackground="#ececec")
        self.ButtonInputImg.configure(activeforeground="#000000")
        self.ButtonInputImg.configure(background="#d9d9d9")
        self.ButtonInputImg.configure(disabledforeground="#a3a3a3")
        self.ButtonInputImg.configure(font="-family {Arial} -size 12")
        self.ButtonInputImg.configure(foreground="#000000")
        self.ButtonInputImg.configure(highlightbackground="#d9d9d9")
        self.ButtonInputImg.configure(highlightcolor="black")
        self.ButtonInputImg.configure(pady="0")
        self.ButtonInputImg.configure(text='''Select Input Image''')
        self.ButtonInputImg.bind('<ButtonRelease-1>',lambda e:stain_selection_gui_support.btn_select_input_img(e))

        self.LabelLowHSV = tk.Label(top)
        self.LabelLowHSV.place(relx=0.075, rely=0.168, height=24, width=285)
        self.LabelLowHSV.configure(activebackground="#f9f9f9")
        self.LabelLowHSV.configure(activeforeground="black")
        self.LabelLowHSV.configure(anchor='w')
        self.LabelLowHSV.configure(background="#d9d9d9")
        self.LabelLowHSV.configure(disabledforeground="#a3a3a3")
        self.LabelLowHSV.configure(font="-family {Arial} -size 12")
        self.LabelLowHSV.configure(foreground="#000000")
        self.LabelLowHSV.configure(highlightbackground="#d9d9d9")
        self.LabelLowHSV.configure(highlightcolor="black")
        self.LabelLowHSV.configure(justify='right')
        self.LabelLowHSV.configure(text='''Enter Lower Threshold  Values (0-255):''')

        self.LabelUpperHSV = tk.Label(top)
        self.LabelUpperHSV.place(relx=0.075, rely=0.306, height=24, width=275)
        self.LabelUpperHSV.configure(activebackground="#f9f9f9")
        self.LabelUpperHSV.configure(activeforeground="black")
        self.LabelUpperHSV.configure(anchor='w')
        self.LabelUpperHSV.configure(background="#d9d9d9")
        self.LabelUpperHSV.configure(disabledforeground="#a3a3a3")
        self.LabelUpperHSV.configure(font="-family {Arial} -size 12")
        self.LabelUpperHSV.configure(foreground="#000000")
        self.LabelUpperHSV.configure(highlightbackground="#d9d9d9")
        self.LabelUpperHSV.configure(highlightcolor="black")
        self.LabelUpperHSV.configure(justify='right')
        self.LabelUpperHSV.configure(text='''Enter Upper Threshold Values (0-255):''')

        self.LabelInputImg = tk.Label(top)
        self.LabelInputImg.place(relx=0.075, rely=0.092, height=24, width=685)
        self.LabelInputImg.configure(activebackground="#f9f9f9")
        self.LabelInputImg.configure(activeforeground="black")
        self.LabelInputImg.configure(anchor='w')
        self.LabelInputImg.configure(background="#d9d9d9")
        self.LabelInputImg.configure(disabledforeground="#a3a3a3")
        self.LabelInputImg.configure(font="-family {Arial} -size 12")
        self.LabelInputImg.configure(foreground="#000000")
        self.LabelInputImg.configure(highlightbackground="#d9d9d9")
        self.LabelInputImg.configure(highlightcolor="black")
        self.LabelInputImg.configure(text='''Input Image:''')

        self.LabelAreaThresh = tk.Label(top)
        self.LabelAreaThresh.place(relx=0.075, rely=0.52, height=24, width=165)
        self.LabelAreaThresh.configure(activebackground="#f9f9f9")
        self.LabelAreaThresh.configure(activeforeground="black")
        self.LabelAreaThresh.configure(anchor='w')
        self.LabelAreaThresh.configure(background="#d9d9d9")
        self.LabelAreaThresh.configure(disabledforeground="#a3a3a3")
        self.LabelAreaThresh.configure(font="-family {Arial} -size 12")
        self.LabelAreaThresh.configure(foreground="#000000")
        self.LabelAreaThresh.configure(highlightbackground="#d9d9d9")
        self.LabelAreaThresh.configure(highlightcolor="black")
        self.LabelAreaThresh.configure(justify='right')
        self.LabelAreaThresh.configure(text='''Enter Area Threshold:''')

        self.ButtonIOutDir = tk.Button(top)
        self.ButtonIOutDir.place(relx=0.075, rely=0.627, height=30, width=141)
        self.ButtonIOutDir.configure(activebackground="#ececec")
        self.ButtonIOutDir.configure(activeforeground="#000000")
        self.ButtonIOutDir.configure(background="#d9d9d9")
        self.ButtonIOutDir.configure(disabledforeground="#a3a3a3")
        self.ButtonIOutDir.configure(font="-family {Arial} -size 12")
        self.ButtonIOutDir.configure(foreground="#000000")
        self.ButtonIOutDir.configure(highlightbackground="#d9d9d9")
        self.ButtonIOutDir.configure(highlightcolor="black")
        self.ButtonIOutDir.configure(pady="0")
        self.ButtonIOutDir.configure(text='''Select Output Dir''')
        self.ButtonIOutDir.bind('<ButtonRelease-1>',lambda e:stain_selection_gui_support.btn_select_output_dir(e))

        self.LabelOutDir = tk.Label(top)
        self.LabelOutDir.place(relx=0.075, rely=0.688, height=24, width=685)
        self.LabelOutDir.configure(activebackground="#f9f9f9")
        self.LabelOutDir.configure(activeforeground="black")
        self.LabelOutDir.configure(anchor='w')
        self.LabelOutDir.configure(background="#d9d9d9")
        self.LabelOutDir.configure(disabledforeground="#a3a3a3")
        self.LabelOutDir.configure(font="-family {Arial} -size 12")
        self.LabelOutDir.configure(foreground="#000000")
        self.LabelOutDir.configure(highlightbackground="#d9d9d9")
        self.LabelOutDir.configure(highlightcolor="black")
        self.LabelOutDir.configure(text='''Output Dir:''')

        self.ButtonSelectStains = tk.Button(top)
        self.ButtonSelectStains.place(relx=0.274, rely=0.765, height=30
                , width=158)
        self.ButtonSelectStains.configure(activebackground="#ececec")
        self.ButtonSelectStains.configure(activeforeground="#000000")
        self.ButtonSelectStains.configure(background="#d9d9d9")
        self.ButtonSelectStains.configure(disabledforeground="#a3a3a3")
        self.ButtonSelectStains.configure(font="-family {Arial} -size 12 -weight bold")
        self.ButtonSelectStains.configure(foreground="#000000")
        self.ButtonSelectStains.configure(highlightbackground="#d9d9d9")
        self.ButtonSelectStains.configure(highlightcolor="black")
        self.ButtonSelectStains.configure(pady="0")
        self.ButtonSelectStains.configure(text='''SELECT STAINS''')
        self.ButtonSelectStains.bind('<ButtonRelease-1>',lambda e:stain_selection_gui_support.btn_select_stains(e))

        self.ButtonExit = tk.Button(top)
        self.ButtonExit.place(relx=0.037, rely=0.856, height=44, width=87)
        self.ButtonExit.configure(activebackground="#ececec")
        self.ButtonExit.configure(activeforeground="#000000")
        self.ButtonExit.configure(background="#d9d9d9")
        self.ButtonExit.configure(disabledforeground="#a3a3a3")
        self.ButtonExit.configure(font="-family {Arial} -size 16 -weight bold")
        self.ButtonExit.configure(foreground="#000000")
        self.ButtonExit.configure(highlightbackground="#d9d9d9")
        self.ButtonExit.configure(highlightcolor="black")
        self.ButtonExit.configure(pady="0")
        self.ButtonExit.configure(text='''EXIT''')
        self.ButtonExit.bind('<Button-1>',lambda e:stain_selection_gui_support.btn_exit(e))

        self.menubar = tk.Menu(top,font=('Arial',12,),bg=_bgcolor,fg=_fgcolor)
        top.configure(menu = self.menubar)

        self.menubar.add_command(
                activebackground="#ececec",
                activeforeground="#000000",
                background="#d9d9d9",
                command=stain_selection_gui_support.prog_descript,
                font="TkDefaultFont",
                foreground="#000000",
                label="Program Description")
        self.menubar.add_separator(
                background="#d9d9d9")
        self.menubar.add_command(
                activebackground="#ececec",
                activeforeground="#000000",
                background="#d9d9d9",
                command=stain_selection_gui_support.prog_instruct,
                font="TkDefaultFont",
                foreground="#000000",
                label="Program Instructions")
        self.menubar.add_separator(
                background="#d9d9d9")
        self.menubar.add_command(
                activebackground="#ececec",
                activeforeground="#000000",
                background="#d9d9d9",
                command=stain_selection_gui_support.quit,
                font="TkDefaultFont",
                foreground="#000000",
                label="Quit")

        self.EntryLowHue = tk.Entry(top)
        self.EntryLowHue.place(relx=0.087, rely=0.245, height=22, relwidth=0.125)

        self.EntryLowHue.configure(background="white")
        self.EntryLowHue.configure(disabledforeground="#a3a3a3")
        self.EntryLowHue.configure(font="-family {Arial} -size 12")
        self.EntryLowHue.configure(foreground="#000000")
        self.EntryLowHue.configure(highlightbackground="#d9d9d9")
        self.EntryLowHue.configure(highlightcolor="black")
        self.EntryLowHue.configure(insertbackground="black")
        self.EntryLowHue.configure(selectbackground="#c4c4c4")
        self.EntryLowHue.configure(selectforeground="black")
        self.EntryLowHue.configure(textvariable=stain_selection_gui_support.low_hue)

        self.EntryLowSat = tk.Entry(top)
        self.EntryLowSat.place(relx=0.237, rely=0.245, height=22, relwidth=0.125)

        self.EntryLowSat.configure(background="white")
        self.EntryLowSat.configure(disabledforeground="#a3a3a3")
        self.EntryLowSat.configure(font="-family {Arial} -size 12")
        self.EntryLowSat.configure(foreground="#000000")
        self.EntryLowSat.configure(highlightbackground="#d9d9d9")
        self.EntryLowSat.configure(highlightcolor="black")
        self.EntryLowSat.configure(insertbackground="black")
        self.EntryLowSat.configure(selectbackground="#c4c4c4")
        self.EntryLowSat.configure(selectforeground="black")
        self.EntryLowSat.configure(textvariable=stain_selection_gui_support.low_sat)

        self.EntryLowVal = tk.Entry(top)
        self.EntryLowVal.place(relx=0.387, rely=0.245, height=22, relwidth=0.125)

        self.EntryLowVal.configure(background="white")
        self.EntryLowVal.configure(disabledforeground="#a3a3a3")
        self.EntryLowVal.configure(font="-family {Arial} -size 12")
        self.EntryLowVal.configure(foreground="#000000")
        self.EntryLowVal.configure(highlightbackground="#d9d9d9")
        self.EntryLowVal.configure(highlightcolor="black")
        self.EntryLowVal.configure(insertbackground="black")
        self.EntryLowVal.configure(selectbackground="#c4c4c4")
        self.EntryLowVal.configure(selectforeground="black")
        self.EntryLowVal.configure(textvariable=stain_selection_gui_support.low_val)

        self.EntryUpHue = tk.Entry(top)
        self.EntryUpHue.place(relx=0.087, rely=0.382,height=22, relwidth=0.125)
        self.EntryUpHue.configure(background="white")
        self.EntryUpHue.configure(disabledforeground="#a3a3a3")
        self.EntryUpHue.configure(font="-family {Arial} -size 12")
        self.EntryUpHue.configure(foreground="#000000")
        self.EntryUpHue.configure(highlightbackground="#d9d9d9")
        self.EntryUpHue.configure(highlightcolor="black")
        self.EntryUpHue.configure(insertbackground="black")
        self.EntryUpHue.configure(selectbackground="#c4c4c4")
        self.EntryUpHue.configure(selectforeground="black")
        self.EntryUpHue.configure(textvariable=stain_selection_gui_support.up_hue)

        self.EntryUpSat = tk.Entry(top)
        self.EntryUpSat.place(relx=0.237, rely=0.382,height=22, relwidth=0.125)
        self.EntryUpSat.configure(background="white")
        self.EntryUpSat.configure(disabledforeground="#a3a3a3")
        self.EntryUpSat.configure(font="-family {Arial} -size 12")
        self.EntryUpSat.configure(foreground="#000000")
        self.EntryUpSat.configure(highlightbackground="#d9d9d9")
        self.EntryUpSat.configure(highlightcolor="black")
        self.EntryUpSat.configure(insertbackground="black")
        self.EntryUpSat.configure(selectbackground="#c4c4c4")
        self.EntryUpSat.configure(selectforeground="black")
        self.EntryUpSat.configure(textvariable=stain_selection_gui_support.up_sat)

        self.EntryUpVal = tk.Entry(top)
        self.EntryUpVal.place(relx=0.387, rely=0.382,height=22, relwidth=0.125)
        self.EntryUpVal.configure(background="white")
        self.EntryUpVal.configure(disabledforeground="#a3a3a3")
        self.EntryUpVal.configure(font="-family {Arial} -size 12")
        self.EntryUpVal.configure(foreground="#000000")
        self.EntryUpVal.configure(highlightbackground="#d9d9d9")
        self.EntryUpVal.configure(highlightcolor="black")
        self.EntryUpVal.configure(insertbackground="black")
        self.EntryUpVal.configure(selectbackground="#c4c4c4")
        self.EntryUpVal.configure(selectforeground="black")
        self.EntryUpVal.configure(textvariable=stain_selection_gui_support.up_val)

        self.EntryGaussianBlur = tk.Entry(top)
        self.EntryGaussianBlur.place(relx=0.087, rely=0.474, height=22
                , relwidth=0.125)
        self.EntryGaussianBlur.configure(background="white")
        self.EntryGaussianBlur.configure(disabledforeground="#a3a3a3")
        self.EntryGaussianBlur.configure(font="-family {Arial} -size 12")
        self.EntryGaussianBlur.configure(foreground="#000000")
        self.EntryGaussianBlur.configure(insertbackground="black")
        self.EntryGaussianBlur.configure(textvariable=stain_selection_gui_support.gaussian_blur)
        self.EntryGaussianBlur.configure(width=104)

        self.EntryAreaThresh = tk.Entry(top)
        self.EntryAreaThresh.place(relx=0.087, rely=0.566, height=22
                , relwidth=0.125)
        self.EntryAreaThresh.configure(background="white")
        self.EntryAreaThresh.configure(disabledforeground="#a3a3a3")
        self.EntryAreaThresh.configure(font="-family {Arial} -size 12")
        self.EntryAreaThresh.configure(foreground="#000000")
        self.EntryAreaThresh.configure(highlightbackground="#d9d9d9")
        self.EntryAreaThresh.configure(highlightcolor="black")
        self.EntryAreaThresh.configure(insertbackground="black")
        self.EntryAreaThresh.configure(selectbackground="#c4c4c4")
        self.EntryAreaThresh.configure(selectforeground="black")
        self.EntryAreaThresh.configure(textvariable=stain_selection_gui_support.area_thresh)
        self.EntryAreaThresh.configure(width=100)

        self.LabelHueLow = tk.Label(top)
        self.LabelHueLow.place(relx=0.087, rely=0.199, height=24, width=34)
        self.LabelHueLow.configure(activebackground="#f9f9f9")
        self.LabelHueLow.configure(activeforeground="black")
        self.LabelHueLow.configure(anchor='w')
        self.LabelHueLow.configure(background="#d9d9d9")
        self.LabelHueLow.configure(disabledforeground="#a3a3a3")
        self.LabelHueLow.configure(font="-family {Arial} -size 12")
        self.LabelHueLow.configure(foreground="#000000")
        self.LabelHueLow.configure(highlightbackground="#d9d9d9")
        self.LabelHueLow.configure(highlightcolor="black")
        self.LabelHueLow.configure(text='''Hue''')

        self.LabelSatLow = tk.Label(top)
        self.LabelSatLow.place(relx=0.237, rely=0.199, height=24, width=77)
        self.LabelSatLow.configure(activebackground="#f9f9f9")
        self.LabelSatLow.configure(activeforeground="black")
        self.LabelSatLow.configure(anchor='w')
        self.LabelSatLow.configure(background="#d9d9d9")
        self.LabelSatLow.configure(disabledforeground="#a3a3a3")
        self.LabelSatLow.configure(font="-family {Arial} -size 12")
        self.LabelSatLow.configure(foreground="#000000")
        self.LabelSatLow.configure(highlightbackground="#d9d9d9")
        self.LabelSatLow.configure(highlightcolor="black")
        self.LabelSatLow.configure(text='''Saturation''')

        self.LabelValueLow = tk.Label(top)
        self.LabelValueLow.place(relx=0.387, rely=0.199, height=24, width=46)
        self.LabelValueLow.configure(activebackground="#f9f9f9")
        self.LabelValueLow.configure(activeforeground="black")
        self.LabelValueLow.configure(anchor='w')
        self.LabelValueLow.configure(background="#d9d9d9")
        self.LabelValueLow.configure(disabledforeground="#a3a3a3")
        self.LabelValueLow.configure(font="-family {Arial} -size 12")
        self.LabelValueLow.configure(foreground="#000000")
        self.LabelValueLow.configure(highlightbackground="#d9d9d9")
        self.LabelValueLow.configure(highlightcolor="black")
        self.LabelValueLow.configure(text='''Value''')

        self.LabelUpSat = tk.Label(top)
        self.LabelUpSat.place(relx=0.237, rely=0.336, height=24, width=84)
        self.LabelUpSat.configure(activebackground="#f9f9f9")
        self.LabelUpSat.configure(activeforeground="black")
        self.LabelUpSat.configure(anchor='w')
        self.LabelUpSat.configure(background="#d9d9d9")
        self.LabelUpSat.configure(disabledforeground="#a3a3a3")
        self.LabelUpSat.configure(font="-family {Arial} -size 12")
        self.LabelUpSat.configure(foreground="#000000")
        self.LabelUpSat.configure(highlightbackground="#d9d9d9")
        self.LabelUpSat.configure(highlightcolor="black")
        self.LabelUpSat.configure(text='''Saturation''')

        self.LabelUpVal = tk.Label(top)
        self.LabelUpVal.place(relx=0.387, rely=0.336, height=24, width=54)
        self.LabelUpVal.configure(activebackground="#f9f9f9")
        self.LabelUpVal.configure(activeforeground="black")
        self.LabelUpVal.configure(anchor='w')
        self.LabelUpVal.configure(background="#d9d9d9")
        self.LabelUpVal.configure(disabledforeground="#a3a3a3")
        self.LabelUpVal.configure(font="-family {Arial} -size 12")
        self.LabelUpVal.configure(foreground="#000000")
        self.LabelUpVal.configure(highlightbackground="#d9d9d9")
        self.LabelUpVal.configure(highlightcolor="black")
        self.LabelUpVal.configure(text='''Value''')

        self.LabelUpHue = tk.Label(top)
        self.LabelUpHue.place(relx=0.087, rely=0.336, height=24, width=34)
        self.LabelUpHue.configure(activebackground="#f9f9f9")
        self.LabelUpHue.configure(activeforeground="black")
        self.LabelUpHue.configure(anchor='w')
        self.LabelUpHue.configure(background="#d9d9d9")
        self.LabelUpHue.configure(disabledforeground="#a3a3a3")
        self.LabelUpHue.configure(font="-family {Arial} -size 12")
        self.LabelUpHue.configure(foreground="#000000")
        self.LabelUpHue.configure(highlightbackground="#d9d9d9")
        self.LabelUpHue.configure(highlightcolor="black")
        self.LabelUpHue.configure(text='''Hue''')

        self.LabelBlur = tk.Label(top)
        self.LabelBlur.place(relx=0.075, rely=0.428, height=24, width=245)
        self.LabelBlur.configure(anchor='w')
        self.LabelBlur.configure(background="#d9d9d9")
        self.LabelBlur.configure(disabledforeground="#a3a3a3")
        self.LabelBlur.configure(font="-family {Arial} -size 12")
        self.LabelBlur.configure(foreground="#000000")
        self.LabelBlur.configure(justify='left')
        self.LabelBlur.configure(text='''Gaussian Blur (ODD Integers Only)''')
        self.LabelBlur.configure(width=245)

if __name__ == '__main__':
    vp_start_gui()





